var hierarchy =
[
    [ "frcsim::RigidBody::AerodynamicGeometry", "structfrcsim_1_1RigidBody_1_1AerodynamicGeometry.html", null ],
    [ "frcsim::Arm", "classfrcsim_1_1Arm.html", null ],
    [ "AutoCloseable", null, [
      [ "jsim.PhysicsWorld", "classjsim_1_1PhysicsWorld.html", null ],
      [ "jsim.nt.WorldPosePublisher", "classjsim_1_1nt_1_1WorldPosePublisher.html", null ]
    ] ],
    [ "frcsim::BallGamepieceSim::BallEntity", "structfrcsim_1_1BallGamepieceSim_1_1BallEntity.html", null ],
    [ "frcsim::BallGamepieceSim", "classfrcsim_1_1BallGamepieceSim.html", [
      [ "frcsim::Season2026BallSim", "classfrcsim_1_1Season2026BallSim.html", null ]
    ] ],
    [ "frcsim::BallPhysicsSim3D", "classfrcsim_1_1BallPhysicsSim3D.html", null ],
    [ "frcsim::BallPhysicsSim3D::BallProperties", "structfrcsim_1_1BallPhysicsSim3D_1_1BallProperties.html", null ],
    [ "frcsim::BallPhysicsSim3D::BallState", "structfrcsim_1_1BallPhysicsSim3D_1_1BallState.html", null ],
    [ "frcsim::BodyFlags", "structfrcsim_1_1BodyFlags.html", null ],
    [ "frcsim::CollisionDetector", "classfrcsim_1_1CollisionDetector.html", null ],
    [ "frcsim::CollisionManifold", "structfrcsim_1_1CollisionManifold.html", null ],
    [ "frcsim::BallPhysicsSim3D::Config", "structfrcsim_1_1BallPhysicsSim3D_1_1Config.html", null ],
    [ "frcsim::DoubleDifferentialMechanism::Config", "structfrcsim_1_1DoubleDifferentialMechanism_1_1Config.html", null ],
    [ "frcsim::IntakeSimulation::Config", "structfrcsim_1_1IntakeSimulation_1_1Config.html", null ],
    [ "frcsim::ShotCalculator3D::Config", "structfrcsim_1_1ShotCalculator3D_1_1Config.html", null ],
    [ "frcsim::TurretFlywheelSim::Config", "structfrcsim_1_1TurretFlywheelSim_1_1Config.html", null ],
    [ "frcsim::IntakeSimulation::ContactEvent", "structfrcsim_1_1IntakeSimulation_1_1ContactEvent.html", null ],
    [ "frcsim::ContactPoint", "structfrcsim_1_1ContactPoint.html", null ],
    [ "frcsim::ContactSolver", "classfrcsim_1_1ContactSolver.html", null ],
    [ "frcsim::FlywheelWheelSim::ControlInput", "structfrcsim_1_1FlywheelWheelSim_1_1ControlInput.html", null ],
    [ "frcsim::DeformableBody", "classfrcsim_1_1DeformableBody.html", null ],
    [ "frcsim::DoubleDifferentialMechanism", "classfrcsim_1_1DoubleDifferentialMechanism.html", null ],
    [ "frcsim::Vector3::DragForceDetails", "structfrcsim_1_1Vector3_1_1DragForceDetails.html", null ],
    [ "frcsim::DragGravityComparison", "structfrcsim_1_1DragGravityComparison.html", null ],
    [ "frcsim::DragModel", "classfrcsim_1_1DragModel.html", null ],
    [ "frcsim::Vector3::DragVector", "structfrcsim_1_1Vector3_1_1DragVector.html", null ],
    [ "frcsim::Elevator", "classfrcsim_1_1Elevator.html", null ],
    [ "frcsim::EncoderSim", "classfrcsim_1_1EncoderSim.html", null ],
    [ "frcsim::EnvironmentalBoundary", "structfrcsim_1_1EnvironmentalBoundary.html", null ],
    [ "frcsim::BallGamepieceSim::ExitTrajectoryParameters", "structfrcsim_1_1BallGamepieceSim_1_1ExitTrajectoryParameters.html", null ],
    [ "frcsim::BallGamepieceSim::FieldConfig", "structfrcsim_1_1BallGamepieceSim_1_1FieldConfig.html", null ],
    [ "jsim.field.FieldConfig", "classjsim_1_1field_1_1FieldConfig.html", null ],
    [ "jsim.field.FieldDefinitionCatalog", "classjsim_1_1field_1_1FieldDefinitionCatalog.html", null ],
    [ "jsim.field.FieldElement", "classjsim_1_1field_1_1FieldElement.html", null ],
    [ "frcsim::FieldObstacle", "structfrcsim_1_1FieldObstacle.html", null ],
    [ "frcsim::FieldObstacleMap", "structfrcsim_1_1FieldObstacleMap.html", null ],
    [ "jsim.api.FieldState&lt; T &gt;", "classjsim_1_1api_1_1FieldState.html", null ],
    [ "frcsim::FieldWall", "structfrcsim_1_1FieldWall.html", null ],
    [ "frcsim::FlywheelWheelSim", "classfrcsim_1_1FlywheelWheelSim.html", null ],
    [ "frcsim::ForceGenerator", "classfrcsim_1_1ForceGenerator.html", [
      [ "frcsim::GravityForce", "classfrcsim_1_1GravityForce.html", null ],
      [ "frcsim::MotorForce", "classfrcsim_1_1MotorForce.html", null ],
      [ "frcsim::SpringForce", "classfrcsim_1_1SpringForce.html", null ]
    ] ],
    [ "frcsim::BallGamepieceSim::GamePieceInfo", "structfrcsim_1_1BallGamepieceSim_1_1GamePieceInfo.html", null ],
    [ "jsim.api.GamePiecePhysics", "classjsim_1_1api_1_1GamePiecePhysics.html", null ],
    [ "jsim.api.GamePieceState", "classjsim_1_1api_1_1GamePieceState.html", [
      [ "jsim.api.gamepieces.Coral2025", "classjsim_1_1api_1_1gamepieces_1_1Coral2025.html", null ],
      [ "jsim.api.gamepieces.Fuel2026", "classjsim_1_1api_1_1gamepieces_1_1Fuel2026.html", null ]
    ] ],
    [ "frcsim::GoalStructure", "structfrcsim_1_1GoalStructure.html", null ],
    [ "frcsim::BallGamepieceSim::GoalZone", "structfrcsim_1_1BallGamepieceSim_1_1GoalZone.html", null ],
    [ "frcsim::GyroSim", "classfrcsim_1_1GyroSim.html", null ],
    [ "frcsim::IntakeSimulation", "classfrcsim_1_1IntakeSimulation.html", null ],
    [ "frcsim::Integrator", "structfrcsim_1_1Integrator.html", null ],
    [ "frcsim::DoubleDifferentialMechanism::InverseResult", "structfrcsim_1_1DoubleDifferentialMechanism_1_1InverseResult.html", null ],
    [ "frcsim::JointBase", "classfrcsim_1_1JointBase.html", [
      [ "frcsim::FixedJoint", "classfrcsim_1_1FixedJoint.html", null ],
      [ "frcsim::PrismaticJoint", "classfrcsim_1_1PrismaticJoint.html", null ],
      [ "frcsim::RevoluteJoint", "classfrcsim_1_1RevoluteJoint.html", null ]
    ] ],
    [ "frcsim::DoubleDifferentialMechanism::JointState", "structfrcsim_1_1DoubleDifferentialMechanism_1_1JointState.html", null ],
    [ "jsim.jni.JSimJNI", "classjsim_1_1jni_1_1JSimJNI.html", null ],
    [ "jsim.api.GamePieceState.Lifecycle", "enumjsim_1_1api_1_1GamePieceState_1_1Lifecycle.html", null ],
    [ "frcsim::DoubleDifferentialMechanism::Limits", "structfrcsim_1_1DoubleDifferentialMechanism_1_1Limits.html", null ],
    [ "frcsim::MagnusModel", "classfrcsim_1_1MagnusModel.html", null ],
    [ "frcsim::Material", "structfrcsim_1_1Material.html", null ],
    [ "frcsim::PhysicsWorld::MaterialInteraction", "structfrcsim_1_1PhysicsWorld_1_1MaterialInteraction.html", null ],
    [ "frcsim::Matrix3", "structfrcsim_1_1Matrix3.html", null ],
    [ "frcsim::MecanumModel", "classfrcsim_1_1MecanumModel.html", null ],
    [ "frcsim::FlywheelWheelSim::MotorConfig", "structfrcsim_1_1FlywheelWheelSim_1_1MotorConfig.html", null ],
    [ "frcsim::DoubleDifferentialMechanism::MotorState", "structfrcsim_1_1DoubleDifferentialMechanism_1_1MotorState.html", null ],
    [ "jsim.PhysicsBody", "classjsim_1_1PhysicsBody.html", null ],
    [ "frcsim::PhysicsConfig", "structfrcsim_1_1PhysicsConfig.html", null ],
    [ "frcsim::PhysicsWorld", "classfrcsim_1_1PhysicsWorld.html", null ],
    [ "frcsim::BallPhysicsSim3D::PickupRequest", "structfrcsim_1_1BallPhysicsSim3D_1_1PickupRequest.html", null ],
    [ "frcsim::BallGamepieceSim::ProjectileEntity", "structfrcsim_1_1BallGamepieceSim_1_1ProjectileEntity.html", null ],
    [ "frcsim::Quaternion", "structfrcsim_1_1Quaternion.html", null ],
    [ "frcsim::RigidAssembly", "classfrcsim_1_1RigidAssembly.html", null ],
    [ "frcsim::RigidBody", "classfrcsim_1_1RigidBody.html", null ],
    [ "jsim.api.RobotID", "enumjsim_1_1api_1_1RobotID.html", null ],
    [ "frcsim::BallGamepieceSim::RobotState", "structfrcsim_1_1BallGamepieceSim_1_1RobotState.html", null ],
    [ "frcsim::Shape", "classfrcsim_1_1Shape.html", [
      [ "frcsim::Box", "classfrcsim_1_1Box.html", null ],
      [ "frcsim::Cylinder", "classfrcsim_1_1Cylinder.html", null ],
      [ "frcsim::Sphere", "classfrcsim_1_1Sphere.html", null ]
    ] ],
    [ "frcsim::ShotCalculator3D", "classfrcsim_1_1ShotCalculator3D.html", null ],
    [ "frcsim::ShotCalculator3D::ShotParameters", "structfrcsim_1_1ShotCalculator3D_1_1ShotParameters.html", null ],
    [ "jsim.api.SimRobot", "classjsim_1_1api_1_1SimRobot.html", null ],
    [ "frcsim::aerodynamics::SpinDecayModel", "classfrcsim_1_1aerodynamics_1_1SpinDecayModel.html", null ],
    [ "jsim.api.StateManager", "classjsim_1_1api_1_1StateManager.html", null ],
    [ "frcsim::SwerveModel", "classfrcsim_1_1SwerveModel.html", null ],
    [ "frcsim::SwerveModuleState", "structfrcsim_1_1SwerveModuleState.html", null ],
    [ "frcsim::ShotCalculator3D::TablePoint", "structfrcsim_1_1ShotCalculator3D_1_1TablePoint.html", null ],
    [ "frcsim::TankModel", "classfrcsim_1_1TankModel.html", null ],
    [ "frcsim::TurretFlywheelSim", "classfrcsim_1_1TurretFlywheelSim.html", null ],
    [ "jsim.field.FieldElement.Type", "enumjsim_1_1field_1_1FieldElement_1_1Type.html", null ],
    [ "frcsim::Vector3", "structfrcsim_1_1Vector3.html", null ],
    [ "frcsim::VisionSim", "classfrcsim_1_1VisionSim.html", null ],
    [ "frcsim::FlywheelWheelSim::WheelConfig", "structfrcsim_1_1FlywheelWheelSim_1_1WheelConfig.html", null ]
];