# Deploy MkDocs docs to rensim.dev

name: Deploy docs to rensim.dev

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install MkDocs and Material theme
        run: |
          pip install mkdocs mkdocs-material
      - name: Build and Deploy
        run: |
          mkdocs gh-deploy --force --config-file mkdocs/mkdocs.yml
