# Deploy Vendordep and MkDocs docs to jsim.dev

name: Deploy vendordep and docs to jsim.dev

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version number"
        type: string
        required: true

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      releaseVersion: ${{ inputs.releaseVersion }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install docs toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
          pip install mkdocs mkdocs-material ghp-import
      # TODO: Remove when SC
      - name: Install roboRio toolchain
        working-directory: vendordep
        run: ./gradlew installRoboRioToolchain
        
      - name: Generate maven and API docs
        working-directory: vendordep
        run: |
          ./gradlew publish
      - name: Build docs site and stage API references
        run: |
          mkdocs build --config-file mkdocs/mkdocs.yml

          mkdir -p mkdocs/site/api/javadoc
          mkdir -p mkdocs/site/api/doxygen

          rsync -a --delete vendordep/build/docs/javadoc/ mkdocs/site/api/javadoc/
          rsync -a --delete vendordep/build/docs/doxygen/ mkdocs/site/api/doxygen/
      # TODO: Preserve old versions using git checkout gh-pages -- maven/
      - name: Stage maven on docs site
        run: |
          mkdir -p mkdocs/site/maven
          mv vendordep/build/repos/JSim.json mkdocs/site/
          rsync -a --delete vendordep/build/maven/ mkdocs/site/maven/
      - name: Output tree
        run: |
          find mkdocs/site -type f
      - name: Configure git identity for deployment
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Deploy
        run: |
          ghp-import -n -p -f mkdocs/site
